#!/bin/bash

#DO NOT EDIT
settings_template="
#Generated by setup.sh
#Read entire file carefully and edit with caution
#
#Directory to put patches in
# 	Directory structure is as such:
# 	patch_dir/{commits,tags,dev}
patch_dir=.patches
#Feature switches. 1 means yes, 0 means no, obviously.

#Should we generate patches per {commit,tag,by branch}?
patch_commits=1
patch_tags=1
patch_dev=1

#Feed the patch to less for review before generating?
review_patches=1
"

if [ ! -d .patches ]; then 
	echo "Creating default directory .patches
	NOTE: You can edit this in .patches_settings which will be
	generated during this script"
	mkdir .patches
	mkdir .patches/commits
	mkdir .patches/tags
	mkdir .patches/dev
fi

if [ ! -f ".patch_settings" ]; then
	printf "Creating .patch_settings\n"
	printf "$settings_template" > .patch_settings
fi

printf "All done.\n"
